Clarify instructions and remove redundant code
RunestoneInteractive/fopp pull request #369
Opened 2024-01-18 09:28 UTC by Nagidrop

2024-01-18 23:59 UTC, bnmnetp requested changes

2024-01-18 23:59 UTC, bnmnetp commented on _sources/Dictionaries/Exercises.rst
> +		def foo(s):
All our examples and other code use 4 space indentation.  Please change this to match.

2024-01-18 23:59 UTC, bnmnetp commented on _sources/AdvancedAccumulation/zip.rst
> +   L3 = list(map(lambda x: x[0] + x[1], zip(L1, L2)))
good catch

2024-01-20 06:46 UTC, Nagidrop commented
I have removed the extra spaces. Also, many thanks for making this course free and publicly available 😄

2024-01-20 17:13 UTC, bnmnetp approved these changes

2024-01-20 17:13 UTC, merged